apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore: 
    fsType: ext4
    volumeID: $VOLUME_ID(You have to fill it manually)
